// Mocks generated by Mockito 5.4.5 from annotations
// in movieverse/test/helpers/test_helper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:convert' as _i28;
import 'dart:typed_data' as _i29;

import 'package:dartz/dartz.dart' as _i4;
import 'package:http/http.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:movieverse/data/datasources/database/firebase_helper.dart'
    as _i6;
import 'package:movieverse/data/datasources/localDataSource/shared_preference_helper.dart'
    as _i10;
import 'package:movieverse/data/datasources/remoteDataSource/remote_data_source.dart'
    as _i12;
import 'package:movieverse/data/models/movie/movie_detail_model.dart' as _i14;
import 'package:movieverse/data/models/movie/movie_model.dart' as _i13;
import 'package:movieverse/data/models/tv/tv_series_detail_model.dart' as _i16;
import 'package:movieverse/data/models/tv/tv_series_model.dart' as _i15;
import 'package:movieverse/data/models/user_model.dart' as _i2;
import 'package:movieverse/data/models/watchlist_item_model.dart' as _i9;
import 'package:movieverse/data/services/api_result.dart' as _i3;
import 'package:movieverse/domain/entities/movie/movie.dart' as _i23;
import 'package:movieverse/domain/entities/movie/movie_detail.dart' as _i24;
import 'package:movieverse/domain/entities/tv/tv_series.dart' as _i25;
import 'package:movieverse/domain/entities/tv/tv_series_detail.dart' as _i26;
import 'package:movieverse/domain/entities/user_entity.dart' as _i19;
import 'package:movieverse/domain/entities/watchlist_item.dart' as _i20;
import 'package:movieverse/domain/repositories/firebase_repository.dart'
    as _i17;
import 'package:movieverse/domain/repositories/repository.dart' as _i21;
import 'package:movieverse/domain/repositories/shared_preference_repository.dart'
    as _i27;
import 'package:movieverse/utils/database_exceptions.dart' as _i18;
import 'package:movieverse/utils/network_exceptions.dart' as _i22;
import 'package:shared_preferences/shared_preferences.dart' as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUserModel_0 extends _i1.SmartFake implements _i2.UserModel {
  _FakeUserModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeApiResult_1<T> extends _i1.SmartFake implements _i3.ApiResult<T> {
  _FakeApiResult_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_2<L, R> extends _i1.SmartFake implements _i4.Either<L, R> {
  _FakeEither_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponse_3 extends _i1.SmartFake implements _i5.Response {
  _FakeResponse_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamedResponse_4 extends _i1.SmartFake
    implements _i5.StreamedResponse {
  _FakeStreamedResponse_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [FirebaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseHelper extends _i1.Mock implements _i6.FirebaseHelper {
  MockFirebaseHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<void> registerUser(
    String? name,
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#registerUser, [name, email, password]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> loginUser(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#loginUser, [email, password]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i2.UserModel> getUserData() =>
      (super.noSuchMethod(
            Invocation.method(#getUserData, []),
            returnValue: _i7.Future<_i2.UserModel>.value(
              _FakeUserModel_0(this, Invocation.method(#getUserData, [])),
            ),
          )
          as _i7.Future<_i2.UserModel>);

  @override
  _i7.Future<String> addToWatchlist(
    String? id,
    String? name,
    String? posterPath,
    String? release,
    bool? isMovie,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addToWatchlist, [
              id,
              name,
              posterPath,
              release,
              isMovie,
            ]),
            returnValue: _i7.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#addToWatchlist, [
                  id,
                  name,
                  posterPath,
                  release,
                  isMovie,
                ]),
              ),
            ),
          )
          as _i7.Future<String>);

  @override
  _i7.Future<String> removeFromWatchlist(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#removeFromWatchlist, [id]),
            returnValue: _i7.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#removeFromWatchlist, [id]),
              ),
            ),
          )
          as _i7.Future<String>);

  @override
  _i7.Future<List<_i9.WatchlistItemModel>> getWatchlist() =>
      (super.noSuchMethod(
            Invocation.method(#getWatchlist, []),
            returnValue: _i7.Future<List<_i9.WatchlistItemModel>>.value(
              <_i9.WatchlistItemModel>[],
            ),
          )
          as _i7.Future<List<_i9.WatchlistItemModel>>);

  @override
  _i7.Future<bool> getWatchlistById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getWatchlistById, [id]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> getCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, []),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> logoutUser() =>
      (super.noSuchMethod(
            Invocation.method(#logoutUser, []),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);
}

/// A class which mocks [SharedPreferenceHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedPreferenceHelper extends _i1.Mock
    implements _i10.SharedPreferenceHelper {
  MockSharedPreferenceHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<String?> getEmail() =>
      (super.noSuchMethod(
            Invocation.method(#getEmail, []),
            returnValue: _i7.Future<String?>.value(),
          )
          as _i7.Future<String?>);

  @override
  _i7.Future<String?> getPassword() =>
      (super.noSuchMethod(
            Invocation.method(#getPassword, []),
            returnValue: _i7.Future<String?>.value(),
          )
          as _i7.Future<String?>);

  @override
  _i7.Future<void> setEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#setEmail, [email]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> setPassword(String? password) =>
      (super.noSuchMethod(
            Invocation.method(#setPassword, [password]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<bool> getOnboardingComplete() =>
      (super.noSuchMethod(
            Invocation.method(#getOnboardingComplete, []),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<void> saveOnboardingComplete() =>
      (super.noSuchMethod(
            Invocation.method(#saveOnboardingComplete, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}

/// A class which mocks [SharedPreferences].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedPreferences extends _i1.Mock implements _i11.SharedPreferences {
  MockSharedPreferences() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Set<String> getKeys() =>
      (super.noSuchMethod(
            Invocation.method(#getKeys, []),
            returnValue: <String>{},
          )
          as Set<String>);

  @override
  Object? get(String? key) =>
      (super.noSuchMethod(Invocation.method(#get, [key])) as Object?);

  @override
  bool? getBool(String? key) =>
      (super.noSuchMethod(Invocation.method(#getBool, [key])) as bool?);

  @override
  int? getInt(String? key) =>
      (super.noSuchMethod(Invocation.method(#getInt, [key])) as int?);

  @override
  double? getDouble(String? key) =>
      (super.noSuchMethod(Invocation.method(#getDouble, [key])) as double?);

  @override
  String? getString(String? key) =>
      (super.noSuchMethod(Invocation.method(#getString, [key])) as String?);

  @override
  bool containsKey(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#containsKey, [key]),
            returnValue: false,
          )
          as bool);

  @override
  List<String>? getStringList(String? key) =>
      (super.noSuchMethod(Invocation.method(#getStringList, [key]))
          as List<String>?);

  @override
  _i7.Future<bool> setBool(String? key, bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setBool, [key, value]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> setInt(String? key, int? value) =>
      (super.noSuchMethod(
            Invocation.method(#setInt, [key, value]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> setDouble(String? key, double? value) =>
      (super.noSuchMethod(
            Invocation.method(#setDouble, [key, value]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> setString(String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setString, [key, value]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> setStringList(String? key, List<String>? value) =>
      (super.noSuchMethod(
            Invocation.method(#setStringList, [key, value]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> remove(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#remove, [key]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> commit() =>
      (super.noSuchMethod(
            Invocation.method(#commit, []),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> clear() =>
      (super.noSuchMethod(
            Invocation.method(#clear, []),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<void> reload() =>
      (super.noSuchMethod(
            Invocation.method(#reload, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}

/// A class which mocks [RemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoteDataSource extends _i1.Mock implements _i12.RemoteDataSource {
  MockRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i3.ApiResult<List<_i13.MovieModel>>> getPopularMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getPopularMovies, []),
            returnValue: _i7.Future<_i3.ApiResult<List<_i13.MovieModel>>>.value(
              _FakeApiResult_1<List<_i13.MovieModel>>(
                this,
                Invocation.method(#getPopularMovies, []),
              ),
            ),
          )
          as _i7.Future<_i3.ApiResult<List<_i13.MovieModel>>>);

  @override
  _i7.Future<_i3.ApiResult<List<_i13.MovieModel>>> getTopRatedMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getTopRatedMovies, []),
            returnValue: _i7.Future<_i3.ApiResult<List<_i13.MovieModel>>>.value(
              _FakeApiResult_1<List<_i13.MovieModel>>(
                this,
                Invocation.method(#getTopRatedMovies, []),
              ),
            ),
          )
          as _i7.Future<_i3.ApiResult<List<_i13.MovieModel>>>);

  @override
  _i7.Future<_i3.ApiResult<List<_i13.MovieModel>>> getNowPlayingMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getNowPlayingMovies, []),
            returnValue: _i7.Future<_i3.ApiResult<List<_i13.MovieModel>>>.value(
              _FakeApiResult_1<List<_i13.MovieModel>>(
                this,
                Invocation.method(#getNowPlayingMovies, []),
              ),
            ),
          )
          as _i7.Future<_i3.ApiResult<List<_i13.MovieModel>>>);

  @override
  _i7.Future<_i3.ApiResult<List<_i13.MovieModel>>> getDiscoverMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getDiscoverMovies, []),
            returnValue: _i7.Future<_i3.ApiResult<List<_i13.MovieModel>>>.value(
              _FakeApiResult_1<List<_i13.MovieModel>>(
                this,
                Invocation.method(#getDiscoverMovies, []),
              ),
            ),
          )
          as _i7.Future<_i3.ApiResult<List<_i13.MovieModel>>>);

  @override
  _i7.Future<_i3.ApiResult<List<_i13.MovieModel>>> getTrendingMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getTrendingMovies, []),
            returnValue: _i7.Future<_i3.ApiResult<List<_i13.MovieModel>>>.value(
              _FakeApiResult_1<List<_i13.MovieModel>>(
                this,
                Invocation.method(#getTrendingMovies, []),
              ),
            ),
          )
          as _i7.Future<_i3.ApiResult<List<_i13.MovieModel>>>);

  @override
  _i7.Future<_i3.ApiResult<List<_i13.MovieModel>>> getUpcomingMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getUpcomingMovies, []),
            returnValue: _i7.Future<_i3.ApiResult<List<_i13.MovieModel>>>.value(
              _FakeApiResult_1<List<_i13.MovieModel>>(
                this,
                Invocation.method(#getUpcomingMovies, []),
              ),
            ),
          )
          as _i7.Future<_i3.ApiResult<List<_i13.MovieModel>>>);

  @override
  _i7.Future<_i3.ApiResult<_i14.MovieDetailResponse>> getMovieDetail(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getMovieDetail, [id]),
            returnValue:
                _i7.Future<_i3.ApiResult<_i14.MovieDetailResponse>>.value(
                  _FakeApiResult_1<_i14.MovieDetailResponse>(
                    this,
                    Invocation.method(#getMovieDetail, [id]),
                  ),
                ),
          )
          as _i7.Future<_i3.ApiResult<_i14.MovieDetailResponse>>);

  @override
  _i7.Future<_i3.ApiResult<List<_i13.MovieModel>>> getMovieRecommendations(
    int? id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMovieRecommendations, [id]),
            returnValue: _i7.Future<_i3.ApiResult<List<_i13.MovieModel>>>.value(
              _FakeApiResult_1<List<_i13.MovieModel>>(
                this,
                Invocation.method(#getMovieRecommendations, [id]),
              ),
            ),
          )
          as _i7.Future<_i3.ApiResult<List<_i13.MovieModel>>>);

  @override
  _i7.Future<_i3.ApiResult<List<_i13.MovieModel>>> searchMovies(
    String? query,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#searchMovies, [query]),
            returnValue: _i7.Future<_i3.ApiResult<List<_i13.MovieModel>>>.value(
              _FakeApiResult_1<List<_i13.MovieModel>>(
                this,
                Invocation.method(#searchMovies, [query]),
              ),
            ),
          )
          as _i7.Future<_i3.ApiResult<List<_i13.MovieModel>>>);

  @override
  _i7.Future<_i3.ApiResult<List<_i15.TvSeriesModel>>>
  getAiringTodayTvSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getAiringTodayTvSeries, []),
            returnValue:
                _i7.Future<_i3.ApiResult<List<_i15.TvSeriesModel>>>.value(
                  _FakeApiResult_1<List<_i15.TvSeriesModel>>(
                    this,
                    Invocation.method(#getAiringTodayTvSeries, []),
                  ),
                ),
          )
          as _i7.Future<_i3.ApiResult<List<_i15.TvSeriesModel>>>);

  @override
  _i7.Future<_i3.ApiResult<List<_i15.TvSeriesModel>>> getPopularTvSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getPopularTvSeries, []),
            returnValue:
                _i7.Future<_i3.ApiResult<List<_i15.TvSeriesModel>>>.value(
                  _FakeApiResult_1<List<_i15.TvSeriesModel>>(
                    this,
                    Invocation.method(#getPopularTvSeries, []),
                  ),
                ),
          )
          as _i7.Future<_i3.ApiResult<List<_i15.TvSeriesModel>>>);

  @override
  _i7.Future<_i3.ApiResult<List<_i15.TvSeriesModel>>> getTopRatedTvSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getTopRatedTvSeries, []),
            returnValue:
                _i7.Future<_i3.ApiResult<List<_i15.TvSeriesModel>>>.value(
                  _FakeApiResult_1<List<_i15.TvSeriesModel>>(
                    this,
                    Invocation.method(#getTopRatedTvSeries, []),
                  ),
                ),
          )
          as _i7.Future<_i3.ApiResult<List<_i15.TvSeriesModel>>>);

  @override
  _i7.Future<_i3.ApiResult<List<_i15.TvSeriesModel>>> getDiscoverTvSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getDiscoverTvSeries, []),
            returnValue:
                _i7.Future<_i3.ApiResult<List<_i15.TvSeriesModel>>>.value(
                  _FakeApiResult_1<List<_i15.TvSeriesModel>>(
                    this,
                    Invocation.method(#getDiscoverTvSeries, []),
                  ),
                ),
          )
          as _i7.Future<_i3.ApiResult<List<_i15.TvSeriesModel>>>);

  @override
  _i7.Future<_i3.ApiResult<List<_i15.TvSeriesModel>>> getTrendingTvSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getTrendingTvSeries, []),
            returnValue:
                _i7.Future<_i3.ApiResult<List<_i15.TvSeriesModel>>>.value(
                  _FakeApiResult_1<List<_i15.TvSeriesModel>>(
                    this,
                    Invocation.method(#getTrendingTvSeries, []),
                  ),
                ),
          )
          as _i7.Future<_i3.ApiResult<List<_i15.TvSeriesModel>>>);

  @override
  _i7.Future<_i3.ApiResult<List<_i15.TvSeriesModel>>> getOnTheAirTvSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getOnTheAirTvSeries, []),
            returnValue:
                _i7.Future<_i3.ApiResult<List<_i15.TvSeriesModel>>>.value(
                  _FakeApiResult_1<List<_i15.TvSeriesModel>>(
                    this,
                    Invocation.method(#getOnTheAirTvSeries, []),
                  ),
                ),
          )
          as _i7.Future<_i3.ApiResult<List<_i15.TvSeriesModel>>>);

  @override
  _i7.Future<_i3.ApiResult<_i16.TvSeriesDetailModel>> getTvSeriesDetail(
    int? id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTvSeriesDetail, [id]),
            returnValue:
                _i7.Future<_i3.ApiResult<_i16.TvSeriesDetailModel>>.value(
                  _FakeApiResult_1<_i16.TvSeriesDetailModel>(
                    this,
                    Invocation.method(#getTvSeriesDetail, [id]),
                  ),
                ),
          )
          as _i7.Future<_i3.ApiResult<_i16.TvSeriesDetailModel>>);

  @override
  _i7.Future<_i3.ApiResult<List<_i15.TvSeriesModel>>>
  getTvSeriesRecommendations(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTvSeriesRecommendations, [id]),
            returnValue:
                _i7.Future<_i3.ApiResult<List<_i15.TvSeriesModel>>>.value(
                  _FakeApiResult_1<List<_i15.TvSeriesModel>>(
                    this,
                    Invocation.method(#getTvSeriesRecommendations, [id]),
                  ),
                ),
          )
          as _i7.Future<_i3.ApiResult<List<_i15.TvSeriesModel>>>);

  @override
  _i7.Future<_i3.ApiResult<List<_i15.TvSeriesModel>>> searchTvSeries(
    String? query,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#searchTvSeries, [query]),
            returnValue:
                _i7.Future<_i3.ApiResult<List<_i15.TvSeriesModel>>>.value(
                  _FakeApiResult_1<List<_i15.TvSeriesModel>>(
                    this,
                    Invocation.method(#searchTvSeries, [query]),
                  ),
                ),
          )
          as _i7.Future<_i3.ApiResult<List<_i15.TvSeriesModel>>>);
}

/// A class which mocks [FirebaseRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseRepository extends _i1.Mock
    implements _i17.FirebaseRepository {
  MockFirebaseRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i4.Either<_i18.DatabaseException, void>> registerUser(
    String? name,
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#registerUser, [name, email, password]),
            returnValue:
                _i7.Future<_i4.Either<_i18.DatabaseException, void>>.value(
                  _FakeEither_2<_i18.DatabaseException, void>(
                    this,
                    Invocation.method(#registerUser, [name, email, password]),
                  ),
                ),
          )
          as _i7.Future<_i4.Either<_i18.DatabaseException, void>>);

  @override
  _i7.Future<_i4.Either<_i18.DatabaseException, void>> loginUser(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#loginUser, [email, password]),
            returnValue:
                _i7.Future<_i4.Either<_i18.DatabaseException, void>>.value(
                  _FakeEither_2<_i18.DatabaseException, void>(
                    this,
                    Invocation.method(#loginUser, [email, password]),
                  ),
                ),
          )
          as _i7.Future<_i4.Either<_i18.DatabaseException, void>>);

  @override
  _i7.Future<_i4.Either<_i18.DatabaseException, _i19.UserEntity>>
  getUserData() =>
      (super.noSuchMethod(
            Invocation.method(#getUserData, []),
            returnValue: _i7.Future<
              _i4.Either<_i18.DatabaseException, _i19.UserEntity>
            >.value(
              _FakeEither_2<_i18.DatabaseException, _i19.UserEntity>(
                this,
                Invocation.method(#getUserData, []),
              ),
            ),
          )
          as _i7.Future<_i4.Either<_i18.DatabaseException, _i19.UserEntity>>);

  @override
  _i7.Future<_i4.Either<_i18.DatabaseException, String>> addToWatchlist(
    String? id,
    String? name,
    String? posterPath,
    String? release,
    bool? isMovie,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addToWatchlist, [
              id,
              name,
              posterPath,
              release,
              isMovie,
            ]),
            returnValue:
                _i7.Future<_i4.Either<_i18.DatabaseException, String>>.value(
                  _FakeEither_2<_i18.DatabaseException, String>(
                    this,
                    Invocation.method(#addToWatchlist, [
                      id,
                      name,
                      posterPath,
                      release,
                      isMovie,
                    ]),
                  ),
                ),
          )
          as _i7.Future<_i4.Either<_i18.DatabaseException, String>>);

  @override
  _i7.Future<_i4.Either<_i18.DatabaseException, String>> removeFromWatchlist(
    String? id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#removeFromWatchlist, [id]),
            returnValue:
                _i7.Future<_i4.Either<_i18.DatabaseException, String>>.value(
                  _FakeEither_2<_i18.DatabaseException, String>(
                    this,
                    Invocation.method(#removeFromWatchlist, [id]),
                  ),
                ),
          )
          as _i7.Future<_i4.Either<_i18.DatabaseException, String>>);

  @override
  _i7.Future<_i4.Either<_i18.DatabaseException, List<_i20.WatchlistItem>>>
  getWatchlist() =>
      (super.noSuchMethod(
            Invocation.method(#getWatchlist, []),
            returnValue: _i7.Future<
              _i4.Either<_i18.DatabaseException, List<_i20.WatchlistItem>>
            >.value(
              _FakeEither_2<_i18.DatabaseException, List<_i20.WatchlistItem>>(
                this,
                Invocation.method(#getWatchlist, []),
              ),
            ),
          )
          as _i7.Future<
            _i4.Either<_i18.DatabaseException, List<_i20.WatchlistItem>>
          >);

  @override
  _i7.Future<bool> getWatchlistById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getWatchlistById, [id]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> autoLogin() =>
      (super.noSuchMethod(
            Invocation.method(#autoLogin, []),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> logoutUser() =>
      (super.noSuchMethod(
            Invocation.method(#logoutUser, []),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);
}

/// A class which mocks [Repository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRepository extends _i1.Mock implements _i21.Repository {
  MockRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i4.Either<_i22.NetworkExceptions, List<_i23.Movie>>>
  getPopularMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getPopularMovies, []),
            returnValue: _i7.Future<
              _i4.Either<_i22.NetworkExceptions, List<_i23.Movie>>
            >.value(
              _FakeEither_2<_i22.NetworkExceptions, List<_i23.Movie>>(
                this,
                Invocation.method(#getPopularMovies, []),
              ),
            ),
          )
          as _i7.Future<_i4.Either<_i22.NetworkExceptions, List<_i23.Movie>>>);

  @override
  _i7.Future<_i4.Either<_i22.NetworkExceptions, List<_i23.Movie>>>
  getTopRatedMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getTopRatedMovies, []),
            returnValue: _i7.Future<
              _i4.Either<_i22.NetworkExceptions, List<_i23.Movie>>
            >.value(
              _FakeEither_2<_i22.NetworkExceptions, List<_i23.Movie>>(
                this,
                Invocation.method(#getTopRatedMovies, []),
              ),
            ),
          )
          as _i7.Future<_i4.Either<_i22.NetworkExceptions, List<_i23.Movie>>>);

  @override
  _i7.Future<_i4.Either<_i22.NetworkExceptions, List<_i23.Movie>>>
  getNowPlayingMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getNowPlayingMovies, []),
            returnValue: _i7.Future<
              _i4.Either<_i22.NetworkExceptions, List<_i23.Movie>>
            >.value(
              _FakeEither_2<_i22.NetworkExceptions, List<_i23.Movie>>(
                this,
                Invocation.method(#getNowPlayingMovies, []),
              ),
            ),
          )
          as _i7.Future<_i4.Either<_i22.NetworkExceptions, List<_i23.Movie>>>);

  @override
  _i7.Future<_i4.Either<_i22.NetworkExceptions, List<_i23.Movie>>>
  getDiscoverMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getDiscoverMovies, []),
            returnValue: _i7.Future<
              _i4.Either<_i22.NetworkExceptions, List<_i23.Movie>>
            >.value(
              _FakeEither_2<_i22.NetworkExceptions, List<_i23.Movie>>(
                this,
                Invocation.method(#getDiscoverMovies, []),
              ),
            ),
          )
          as _i7.Future<_i4.Either<_i22.NetworkExceptions, List<_i23.Movie>>>);

  @override
  _i7.Future<_i4.Either<_i22.NetworkExceptions, List<_i23.Movie>>>
  getTrendingMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getTrendingMovies, []),
            returnValue: _i7.Future<
              _i4.Either<_i22.NetworkExceptions, List<_i23.Movie>>
            >.value(
              _FakeEither_2<_i22.NetworkExceptions, List<_i23.Movie>>(
                this,
                Invocation.method(#getTrendingMovies, []),
              ),
            ),
          )
          as _i7.Future<_i4.Either<_i22.NetworkExceptions, List<_i23.Movie>>>);

  @override
  _i7.Future<_i4.Either<_i22.NetworkExceptions, List<_i23.Movie>>>
  getUpcomingMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getUpcomingMovies, []),
            returnValue: _i7.Future<
              _i4.Either<_i22.NetworkExceptions, List<_i23.Movie>>
            >.value(
              _FakeEither_2<_i22.NetworkExceptions, List<_i23.Movie>>(
                this,
                Invocation.method(#getUpcomingMovies, []),
              ),
            ),
          )
          as _i7.Future<_i4.Either<_i22.NetworkExceptions, List<_i23.Movie>>>);

  @override
  _i7.Future<_i4.Either<_i22.NetworkExceptions, _i24.MovieDetail>>
  getMovieDetail(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getMovieDetail, [id]),
            returnValue: _i7.Future<
              _i4.Either<_i22.NetworkExceptions, _i24.MovieDetail>
            >.value(
              _FakeEither_2<_i22.NetworkExceptions, _i24.MovieDetail>(
                this,
                Invocation.method(#getMovieDetail, [id]),
              ),
            ),
          )
          as _i7.Future<_i4.Either<_i22.NetworkExceptions, _i24.MovieDetail>>);

  @override
  _i7.Future<_i4.Either<_i22.NetworkExceptions, List<_i23.Movie>>>
  getMovieRecommendations(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getMovieRecommendations, [id]),
            returnValue: _i7.Future<
              _i4.Either<_i22.NetworkExceptions, List<_i23.Movie>>
            >.value(
              _FakeEither_2<_i22.NetworkExceptions, List<_i23.Movie>>(
                this,
                Invocation.method(#getMovieRecommendations, [id]),
              ),
            ),
          )
          as _i7.Future<_i4.Either<_i22.NetworkExceptions, List<_i23.Movie>>>);

  @override
  _i7.Future<_i4.Either<_i22.NetworkExceptions, List<_i23.Movie>>> searchMovies(
    String? query,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#searchMovies, [query]),
            returnValue: _i7.Future<
              _i4.Either<_i22.NetworkExceptions, List<_i23.Movie>>
            >.value(
              _FakeEither_2<_i22.NetworkExceptions, List<_i23.Movie>>(
                this,
                Invocation.method(#searchMovies, [query]),
              ),
            ),
          )
          as _i7.Future<_i4.Either<_i22.NetworkExceptions, List<_i23.Movie>>>);

  @override
  _i7.Future<_i4.Either<_i22.NetworkExceptions, List<_i25.TvSeries>>>
  getAiringTodayTvSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getAiringTodayTvSeries, []),
            returnValue: _i7.Future<
              _i4.Either<_i22.NetworkExceptions, List<_i25.TvSeries>>
            >.value(
              _FakeEither_2<_i22.NetworkExceptions, List<_i25.TvSeries>>(
                this,
                Invocation.method(#getAiringTodayTvSeries, []),
              ),
            ),
          )
          as _i7.Future<
            _i4.Either<_i22.NetworkExceptions, List<_i25.TvSeries>>
          >);

  @override
  _i7.Future<_i4.Either<_i22.NetworkExceptions, List<_i25.TvSeries>>>
  getPopularTvSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getPopularTvSeries, []),
            returnValue: _i7.Future<
              _i4.Either<_i22.NetworkExceptions, List<_i25.TvSeries>>
            >.value(
              _FakeEither_2<_i22.NetworkExceptions, List<_i25.TvSeries>>(
                this,
                Invocation.method(#getPopularTvSeries, []),
              ),
            ),
          )
          as _i7.Future<
            _i4.Either<_i22.NetworkExceptions, List<_i25.TvSeries>>
          >);

  @override
  _i7.Future<_i4.Either<_i22.NetworkExceptions, List<_i25.TvSeries>>>
  getTopRatedTvSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getTopRatedTvSeries, []),
            returnValue: _i7.Future<
              _i4.Either<_i22.NetworkExceptions, List<_i25.TvSeries>>
            >.value(
              _FakeEither_2<_i22.NetworkExceptions, List<_i25.TvSeries>>(
                this,
                Invocation.method(#getTopRatedTvSeries, []),
              ),
            ),
          )
          as _i7.Future<
            _i4.Either<_i22.NetworkExceptions, List<_i25.TvSeries>>
          >);

  @override
  _i7.Future<_i4.Either<_i22.NetworkExceptions, List<_i25.TvSeries>>>
  getDiscoverTvSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getDiscoverTvSeries, []),
            returnValue: _i7.Future<
              _i4.Either<_i22.NetworkExceptions, List<_i25.TvSeries>>
            >.value(
              _FakeEither_2<_i22.NetworkExceptions, List<_i25.TvSeries>>(
                this,
                Invocation.method(#getDiscoverTvSeries, []),
              ),
            ),
          )
          as _i7.Future<
            _i4.Either<_i22.NetworkExceptions, List<_i25.TvSeries>>
          >);

  @override
  _i7.Future<_i4.Either<_i22.NetworkExceptions, List<_i25.TvSeries>>>
  getTrendingTvSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getTrendingTvSeries, []),
            returnValue: _i7.Future<
              _i4.Either<_i22.NetworkExceptions, List<_i25.TvSeries>>
            >.value(
              _FakeEither_2<_i22.NetworkExceptions, List<_i25.TvSeries>>(
                this,
                Invocation.method(#getTrendingTvSeries, []),
              ),
            ),
          )
          as _i7.Future<
            _i4.Either<_i22.NetworkExceptions, List<_i25.TvSeries>>
          >);

  @override
  _i7.Future<_i4.Either<_i22.NetworkExceptions, List<_i25.TvSeries>>>
  getOnTheAirTvSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getOnTheAirTvSeries, []),
            returnValue: _i7.Future<
              _i4.Either<_i22.NetworkExceptions, List<_i25.TvSeries>>
            >.value(
              _FakeEither_2<_i22.NetworkExceptions, List<_i25.TvSeries>>(
                this,
                Invocation.method(#getOnTheAirTvSeries, []),
              ),
            ),
          )
          as _i7.Future<
            _i4.Either<_i22.NetworkExceptions, List<_i25.TvSeries>>
          >);

  @override
  _i7.Future<_i4.Either<_i22.NetworkExceptions, _i26.TvSeriesDetail>>
  getTvSeriesDetail(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTvSeriesDetail, [id]),
            returnValue: _i7.Future<
              _i4.Either<_i22.NetworkExceptions, _i26.TvSeriesDetail>
            >.value(
              _FakeEither_2<_i22.NetworkExceptions, _i26.TvSeriesDetail>(
                this,
                Invocation.method(#getTvSeriesDetail, [id]),
              ),
            ),
          )
          as _i7.Future<
            _i4.Either<_i22.NetworkExceptions, _i26.TvSeriesDetail>
          >);

  @override
  _i7.Future<_i4.Either<_i22.NetworkExceptions, List<_i25.TvSeries>>>
  getTvSeriesRecommendations(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTvSeriesRecommendations, [id]),
            returnValue: _i7.Future<
              _i4.Either<_i22.NetworkExceptions, List<_i25.TvSeries>>
            >.value(
              _FakeEither_2<_i22.NetworkExceptions, List<_i25.TvSeries>>(
                this,
                Invocation.method(#getTvSeriesRecommendations, [id]),
              ),
            ),
          )
          as _i7.Future<
            _i4.Either<_i22.NetworkExceptions, List<_i25.TvSeries>>
          >);

  @override
  _i7.Future<_i4.Either<_i22.NetworkExceptions, List<_i25.TvSeries>>>
  searchTvSeries(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchTvSeries, [query]),
            returnValue: _i7.Future<
              _i4.Either<_i22.NetworkExceptions, List<_i25.TvSeries>>
            >.value(
              _FakeEither_2<_i22.NetworkExceptions, List<_i25.TvSeries>>(
                this,
                Invocation.method(#searchTvSeries, [query]),
              ),
            ),
          )
          as _i7.Future<
            _i4.Either<_i22.NetworkExceptions, List<_i25.TvSeries>>
          >);
}

/// A class which mocks [SharedPreferenceRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedPreferenceRepository extends _i1.Mock
    implements _i27.SharedPreferenceRepository {
  MockSharedPreferenceRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<String?> getEmail() =>
      (super.noSuchMethod(
            Invocation.method(#getEmail, []),
            returnValue: _i7.Future<String?>.value(),
          )
          as _i7.Future<String?>);

  @override
  _i7.Future<String?> getPassword() =>
      (super.noSuchMethod(
            Invocation.method(#getPassword, []),
            returnValue: _i7.Future<String?>.value(),
          )
          as _i7.Future<String?>);

  @override
  _i7.Future<void> saveCredentials(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#saveCredentials, [email, password]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<bool> getOnboardingComplete() =>
      (super.noSuchMethod(
            Invocation.method(#getOnboardingComplete, []),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<void> saveOnboardingComplete() =>
      (super.noSuchMethod(
            Invocation.method(#saveOnboardingComplete, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClient extends _i1.Mock implements _i5.Client {
  MockHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i5.Response> head(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
            Invocation.method(#head, [url], {#headers: headers}),
            returnValue: _i7.Future<_i5.Response>.value(
              _FakeResponse_3(
                this,
                Invocation.method(#head, [url], {#headers: headers}),
              ),
            ),
          )
          as _i7.Future<_i5.Response>);

  @override
  _i7.Future<_i5.Response> get(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
            Invocation.method(#get, [url], {#headers: headers}),
            returnValue: _i7.Future<_i5.Response>.value(
              _FakeResponse_3(
                this,
                Invocation.method(#get, [url], {#headers: headers}),
              ),
            ),
          )
          as _i7.Future<_i5.Response>);

  @override
  _i7.Future<_i5.Response> post(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i28.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i7.Future<_i5.Response>.value(
              _FakeResponse_3(
                this,
                Invocation.method(
                  #post,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i7.Future<_i5.Response>);

  @override
  _i7.Future<_i5.Response> put(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i28.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i7.Future<_i5.Response>.value(
              _FakeResponse_3(
                this,
                Invocation.method(
                  #put,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i7.Future<_i5.Response>);

  @override
  _i7.Future<_i5.Response> patch(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i28.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patch,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i7.Future<_i5.Response>.value(
              _FakeResponse_3(
                this,
                Invocation.method(
                  #patch,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i7.Future<_i5.Response>);

  @override
  _i7.Future<_i5.Response> delete(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i28.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i7.Future<_i5.Response>.value(
              _FakeResponse_3(
                this,
                Invocation.method(
                  #delete,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i7.Future<_i5.Response>);

  @override
  _i7.Future<String> read(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
            Invocation.method(#read, [url], {#headers: headers}),
            returnValue: _i7.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#read, [url], {#headers: headers}),
              ),
            ),
          )
          as _i7.Future<String>);

  @override
  _i7.Future<_i29.Uint8List> readBytes(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#readBytes, [url], {#headers: headers}),
            returnValue: _i7.Future<_i29.Uint8List>.value(_i29.Uint8List(0)),
          )
          as _i7.Future<_i29.Uint8List>);

  @override
  _i7.Future<_i5.StreamedResponse> send(_i5.BaseRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#send, [request]),
            returnValue: _i7.Future<_i5.StreamedResponse>.value(
              _FakeStreamedResponse_4(
                this,
                Invocation.method(#send, [request]),
              ),
            ),
          )
          as _i7.Future<_i5.StreamedResponse>);

  @override
  void close() => super.noSuchMethod(
    Invocation.method(#close, []),
    returnValueForMissingStub: null,
  );
}
